# Site settings
page_title: Catalin Rus - novacard.ro
description: catalinrus novacard profile 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://catalinrus.novacard.ro" # the base hostname & protocol for your site


# Identity
name: Catalin Rus
title:
company:


# Contacts
email: me@catalinrus.com
phone: +40729666966
website: https://catalinrus.com


# Social settings
facebook_url:                                              # https://facebook.com/username/
linkedin_url: https://www.linkedin.com/in/catalin-rus-6b38b864     # https://www.linkedin.com/in/username
instagram_url:                                             # https://www.instagram.com/username
pinterest_url:                                             # https://pinterest.com/username
twitter_url:                                               # https://twitter.com/username
youtube_url:                                               # https://youtube.com/channel/channel-id
snapchat_url:                                              # https://snapchat.com/add/
whatsapp_url:                                              # https://wa.me/your-phone-number-with-country-prefix
tiktok_url:                                                # https://tiktok.com/@username
telegram_url:                                              # https://t.me/username
skype_url:                                                 # https://join.skype.com/invite/user-id
github_url:                                                # https://github.com/username
gitlab_url:                                                # https://gitlab.com/username


# Build settings
markdown: kramdown
